# Requires: proxy, proxy_http, proxy_wstunnel, headers
ProxyPass "/server-console/socket" "ws://127.0.0.1:5091/socket" upgrade=websocket retry=0 timeout=60
ProxyPassReverse "/server-console/socket" "ws://127.0.0.1:5091/socket"
